

import { IOptions, ITimzeZone } from "./../modules/index";
export const timeZones: ITimzeZone[] = [
  { label: "Abu Dhabi", value: "Asia/Dubai" },
  { label: "Amsterdam", value: "Europe/Amsterdam" },
  { label: "Andorra", value: "Europe/Andorra" },
  { label: "Athens", value: "Europe/Athens" },
  { label: "Auckland", value: "Pacific/Auckland" },
  { label: "Baku", value: "Asia/Baku" },
  { label: "Bangkok", value: "Asia/Bangkok" },
  { label: "Beirut", value: "Asia/Beirut" },
  { label: "Berlin", value: "Europe/Berlin" },
  { label: "Brasilia", value: "America/Sao_Paulo" },
  { label: "Brussels", value: "Europe/Brussels" },
  { label: "Bucharest", value: "Europe/Bucharest" },
  { label: "Budapest", value: "Europe/Budapest" },
  { label: "Cairo", value: "Africa/Cairo" },
  { label: "Canberra", value: "Australia/Sydney" },
  { label: "Cape Town", value: "Africa/Johannesburg" },
  { label: "Caracas", value: "America/Caracas" },
  { label: "Chicago", value: "America/Chicago" },
  { label: "Copenhagen", value: "Europe/Copenhagen" },
  { label: "Dhaka", value: "Asia/Dhaka" },
  { label: "Dubai", value: "Asia/Dubai" },
  { label: "Dublin", value: "Europe/Dublin" },
  { label: "Edinburgh", value: "Europe/Edinburgh" },
  { label: "Geneva", value: "Europe/Zurich" },
  { label: "Helsinki", value: "Europe/Helsinki" },
  { label: "Hong Kong", value: "Asia/Hong_Kong" },
  { label: "Istanbul", value: "Europe/Istanbul" },
  { label: "Jakarta", value: "Asia/Jakarta" },
  { label: "Jerusalem", value: "Asia/Jerusalem" },
  { label: "Johannesburg", value: "Africa/Johannesburg" },
  { label: "Kabul", value: "Asia/Kabul" },
  { label: "Kolkata", value: "Asia/Kolkata" },
  { label: "Kuala Lumpur", value: "Asia/Kuala_Lumpur" },
  { label: "Lisbon", value: "Europe/Lisbon" },
  { label: "London", value: "Europe/London" },
  { label: "Los Angeles", value: "America/Los_Angeles" },
  { label: "Madrid", value: "Europe/Madrid" },
  { label: "Manila", value: "Asia/Manila" },
  { label: "Melbourne", value: "Australia/Melbourne" },
  { label: "Mexico City", value: "America/Mexico_City" },
  { label: "Moscow", value: "Europe/Moscow" },
  { label: "Mumbai", value: "Asia/Kolkata" },
  { label: "Nairobi", value: "Africa/Nairobi" },
  { label: "New Delhi", value: "Asia/Kolkata" },
  { label: "New York", value: "America/New_York" },
  { label: "Oslo", value: "Europe/Oslo" },
  { label: "Paris", value: "Europe/Paris" },
  { label: "Prague", value: "Europe/Prague" },
  { label: "Riyadh", value: "Asia/Riyadh" },
  { label: "Rome", value: "Europe/Rome" },
  { label: "San Francisco", value: "America/Los_Angeles" },
  { label: "Sao Paulo", value: "America/Sao_Paulo" },
  { label: "Seoul", value: "Asia/Seoul" },
  { label: "Shanghai", value: "Asia/Shanghai" },
  { label: "Singapore", value: "Asia/Singapore" },
  { label: "Sydney", value: "Australia/Sydney" },
  { label: "Taipei", value: "Asia/Taipei" },
  { label: "Tokyo", value: "Asia/Tokyo" },
  { label: "Toronto", value: "America/Toronto" },
  { label: "Vancouver", value: "America/Vancouver" },
  { label: "Vienna", value: "Europe/Vienna" },
  { label: "Warsaw", value: "Europe/Warsaw" },
  { label: "Washington D.C.", value: "America/New_York" },
  { label: "Wellington", value: "Pacific/Auckland" },
  { label: "Zurich", value: "Europe/Zurich" },
  { label: "Abuja", value: "Africa/Lagos" },
  { label: "Aden", value: "Asia/Aden" },
  { label: "Almaty", value: "Asia/Almaty" },
  { label: "Amman", value: "Asia/Amman" },
  { label: "Anchorage", value: "America/Anchorage" },
  { label: "Antananarivo", value: "Indian/Antananarivo" },
  { label: "Aqtau", value: "Asia/Aqtau" },
  { label: "Aqtobe", value: "Asia/Aqtobe" },
  { label: "Asuncion", value: "America/Asuncion" },
  { label: "Astana", value: "Asia/Astana" },
  { label: "Banjul", value: "Africa/Banjul" },
  { label: "Baku", value: "Asia/Baku" },
  { label: "Barbados", value: "America/Barbados" },
  { label: "Belgrade", value: "Europe/Belgrade" },
  { label: "Berlin", value: "Europe/Berlin" },
  { label: "Bermuda", value: "Atlantic/Bermuda" },
  { label: "Bishkek", value: "Asia/Bishkek" },
  { label: "Brunei", value: "Asia/Brunei" },
  { label: "Bucharest", value: "Europe/Bucharest" },
  { label: "Budapest", value: "Europe/Budapest" },
  { label: "Buenos Aires", value: "America/Argentina/Buenos_Aires" },
  { label: "Cairo", value: "Africa/Cairo" },
  { label: "Canberra", value: "Australia/Canberra" },
  { label: "Casablanca", value: "Africa/Casablanca" },
  { label: "Chengdu", value: "Asia/Chengdu" },
  { label: "Chennai", value: "Asia/Kolkata" },
  { label: "Colombo", value: "Asia/Colombo" },
  { label: "Conakry", value: "Africa/Conakry" },
  { label: "Copenhagen", value: "Europe/Copenhagen" },
  { label: "Dakar", value: "Africa/Dakar" },
  { label: "Dar es Salaam", value: "Africa/Dar_es_Salaam" },
  { label: "Dhaka", value: "Asia/Dhaka" },
  { label: "Dili", value: "Asia/Dili" },
  { label: "Djibouti", value: "Africa/Djibouti" },
  { label: "Dodoma", value: "Africa/Dodoma" },
  { label: "Dushanbe", value: "Asia/Dushanbe" },
  { label: "East Timor", value: "Asia/Dili" },
  { label: "Eindhoven", value: "Europe/Amsterdam" },
  { label: "Freetown", value: "Africa/Freetown" },
  { label: "Galapagos", value: "Pacific/Galapagos" },
  { label: "Gaza", value: "Asia/Gaza" },
  { label: "Gibraltar", value: "Europe/Gibraltar" },
  { label: "Guam", value: "Pacific/Guam" },
  { label: "Helsinki", value: "Europe/Helsinki" },
  { label: "Ho Chi Minh City", value: "Asia/Ho_Chi_Minh" },
  { label: "Hong Kong", value: "Asia/Hong_Kong" },
  { label: "Honiara", value: "Pacific/Honiara" },
  { label: "Islamabad", value: "Asia/Karachi" },
  { label: "Istanbul", value: "Europe/Istanbul" },
  { label: "Jeddah", value: "Asia/Jeddah" },
];
export const getCurrentTime = (timeZone: string) => {
  const options: IOptions = {
    timeZone,
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  };

  return new Intl.DateTimeFormat("tr-TR", options).format(new Date());
};
